# Generated by Django 4.1.6 on 2023-02-06 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=30)),
                ('detalhe_produto', models.TextField(max_length=2000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(max_length=1000000)),
                ('imagem', models.ImageField(upload_to='img')),
                ('data_produto', models.DateTimeField(default=django.utils.timezone.now)),
                ('stoque', models.IntegerField()),
                ('categoria', models.CharField(choices=[('fones', 'Fones de Ouvidos'), ('caixa de som', 'Caixa de Som'), ('receptor', 'Receptores'), ('controles', 'Controles'), ('acessorios', 'Acessorios'), ('video games', 'Video Games e Jogos')], max_length=30)),
            ],
        ),
    ]
